import {toolDialog,localDownload} from '../ui/tool-dialog.js';
import {escapeHTML as esc} from '../ui/icons.js';
import {validateGenome} from '../core/genome.js';
import {REVIEW_POSES} from '../review/foundation.js';
import {buildDelivery,deliveryEligibility} from './delivery.js';
/** Holds one immutable source snapshot. No preview or store mutations. */
export function openDeliveryPanel(raw,preview={}){
  const source=validateGenome(raw),eligibility=deliveryEligibility(source),{dialog,body}=toolDialog('asset-delivery','Export a game asset');
  let job=null,result=null,generation=0;
  body.innerHTML=`<p class="tool-eyebrow">Delivery studio / 11 · local processing</p><p><b>${esc(source.name)}</b> · source <code>${esc(eligibility.sourceFingerprint)}</code></p><div id="delivery-coverage" class="tool-notice ${eligibility.eligible?'':'tool-error'}">${eligibility.eligible?'All attachment families are supported. Export includes all active genes. Inactive genes remain in the source and are listed in the manifest.':`Export blocked. The Inspector cannot draw: <b>${eligibility.unsupportedFamilies.map(esc).join(', ')}</b>. No parts will be removed. Use a supported model or export the source blueprint.`}</div>
<p class="tool-hint">This exports Inspector geometry, not a GPU capture. Motion uses sampled morph targets, not a reusable skeleton. Materials use vertex color and standard PBR values. Fine textures and custom shaders are not included.</p>
<form id="delivery-form"><div class="tool-grid"><label>Asset type<select id="delivery-mode"><option value="static">Static posed model</option><option value="motion">Model + baked motion</option></select></label><label>Mesh layout<select id="delivery-layout"><option value="material" selected>Group by material · fewer meshes</option><option value="separate">Separate meshes · keep components</option></select></label><label>Triangle / mesh budget<select id="delivery-target"><option value="desktop">Desktop · 100k / 150</option><option value="mobile">Mobile · 25k / 60</option><option value="crowd">Crowd · 10k / 24</option></select></label><label data-static>Pose<select id="delivery-pose">${REVIEW_POSES.map(p=>`<option value="${p}" ${p===(preview.pose||'bind')?'selected':''}>${esc(p)}</option>`).join('')}</select></label><label data-static>Pose phase<input id="delivery-phase" type="number" min="0" max="1" step=".01" value="${Number.isFinite(preview.phase)?Math.max(0,Math.min(1,preview.phase)):0.5}"></label><label data-motion hidden>Motion samples<select id="delivery-frames"><option value="9" selected>9 · standard / 8 morph targets</option><option value="17">17 · smoother / 16 targets</option><option value="33">33 · larger file</option></select></label><label data-motion hidden>Clip range<span class="tool-hint" style="display:block;margin-top:8px">One source cycle, from phase 0 to 1. No loop is forced. Playback starts at zero seconds.</span></label></div>
<label class="tool-check"><input id="delivery-pigment" type="checkbox" checked><span>Bake procedural pigment into vertex colors.</span></label><label class="tool-check"><input id="delivery-warnings" type="checkbox"><span>Allow technical warnings. I will review the included audit. Failed checks still block export.</span></label>
<p class="tool-hint">Maximum file size: 64 MiB. Grouping preserves all vertices, triangles, normals, colors, and sampled motion. It combines component nodes. No automatic mesh simplification. More samples increase file size and morph-target count. Check your game importer limits. This job uses a copy of the current blueprint.</p><div class="tool-row"><button id="delivery-build" type="submit" class="tool-primary" ${eligibility.eligible?'':'disabled'}>Build asset package</button><button id="delivery-cancel" type="button" hidden>Cancel build</button><button id="delivery-source" type="button">Source blueprint</button></div></form>
<progress id="delivery-progress" value="0" max="1" hidden></progress><p id="delivery-status" class="tool-status" role="status" aria-live="polite">${eligibility.eligible?'Ready to build. No data leaves this browser.':'Choose a complete Inspector model to export geometry.'}</p><section id="delivery-result" class="tool-results" hidden><h3>Package ready</h3><p id="delivery-summary"></p><p id="delivery-loop" class="tool-hint"></p><div class="tool-row"><button class="tool-primary" id="delivery-zip">Download asset ZIP</button><button id="delivery-glb">Download GLB</button><button id="delivery-audit">Export audit</button></div><p class="tool-hint">ZIP: model.glb, editable source, manifest, audit, and integration notes. File hashes and bounds are in the manifest. Visual approval is still required.</p></section>`;
  const $=s=>body.querySelector(s),setBusy=active=>{$('#delivery-build').disabled=active||!eligibility.eligible;$('#delivery-cancel').hidden=!active;$('#delivery-progress').hidden=!active;for(const el of body.querySelectorAll('select,input'))el.disabled=active;};
  function clearResult(){result=null;$('#delivery-result').hidden=true;}
  $('#delivery-mode').onchange=()=>{for(const el of body.querySelectorAll('[data-static]'))el.hidden=$('#delivery-mode').value==='motion';for(const el of body.querySelectorAll('[data-motion]'))el.hidden=$('#delivery-mode').value!=='motion';};
  $('#delivery-form').addEventListener('change',clearResult);
  $('#delivery-form').onsubmit=async event=>{
    event.preventDefault();if(job||!eligibility.eligible)return;clearResult();const id=++generation;job=new AbortController();setBusy(true);$('#delivery-status').textContent='Prepare source…';
    try{const value=await buildDelivery(source,{mode:$('#delivery-mode').value,meshLayout:$('#delivery-layout').value,pose:$('#delivery-pose').value,phase:Number($('#delivery-phase').value),target:$('#delivery-target').value,frames:Number($('#delivery-frames').value),pigment:$('#delivery-pigment').checked,acknowledgeWarnings:$('#delivery-warnings').checked},{signal:job.signal,onProgress:p=>{if(id!==generation)return;$('#delivery-progress').max=Math.max(1,p.total);$('#delivery-progress').value=p.completed;$('#delivery-status').textContent=`${p.stage} · ${p.completed} / ${p.total}`;}});
      if(id!==generation||!dialog.open)return;result=value;const m=value.manifest;$('#delivery-result').hidden=false;$('#delivery-summary').textContent=`${(value.glb.byteLength/1048576).toFixed(2)} MiB · ${m.totals.triangles.toLocaleString()} triangles · ${m.packing.sourceMeshes} → ${m.totals.meshes} meshes · ${m.animation.samples||1} sample(s).`;
      $('#delivery-loop').textContent=m.settings.mode==='motion'?`Baked clip: ${m.animation.durationSeconds.toFixed(2)} seconds. Endpoint gap: ${m.animation.endpointGapMetres.toFixed(4)} m. ${m.animation.loopClosed?'Geometry endpoints match. Check the motion before looping.':'Endpoints differ. Use one-shot playback unless you edit the motion.'}`:'Static posed geometry. No animation or skeleton is included.';
      $('#delivery-status').textContent=`Ready. Technical result: ${value.report.technicalStatus}. External glTF validation and GPU import are not implied.`;
    }catch(error){if(id===generation&&dialog.open)$('#delivery-status').textContent=error.message;}finally{if(id===generation){job=null;if(dialog.open)setBusy(false);}}
  };
  $('#delivery-cancel').onclick=()=>job?.abort();$('#delivery-source').onclick=()=>localDownload(JSON.stringify(source,null,2), 'source.morph.json');
  $('#delivery-zip').onclick=()=>result&&localDownload(result.zip,result.name+'.asset.zip','application/zip');$('#delivery-glb').onclick=()=>result&&localDownload(result.glb,result.name+'.glb','model/gltf-binary');$('#delivery-audit').onclick=()=>result&&localDownload(JSON.stringify(result.report,null,2),result.name+'.audit.json');
  dialog.addEventListener('close',()=>{generation++;job?.abort();job=null;result=null;});return dialog;
}
