import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {preset} from '../src/core/genome.js';
import {PRESET_MODELS} from '../src/core/presets.js';
import {FoundationCompiler,motionCycleTime} from '../src/review/foundation.js';
import {buildDelivery,deliveryEligibility,deliveryOptions,DELIVERY_LIMITS} from '../src/export/delivery.js';
import {GLBWriter,readDeliveryGLB,deliveryPose} from '../src/export/glb.js';
import {sha256,archive,safeAssetName} from '../src/export/archive.js';
const digest=b=>createHash('sha256').update(b).digest('hex');
for(const input of ['', 'abc','A'.repeat(55),'B'.repeat(56),'C'.repeat(63),'D'.repeat(64),'E'.repeat(65),'生物 / é\n',new Uint8Array(100003).map((_,i)=>i%255)])test('SHA-256 matches Node crypto: '+(typeof input==='string'?input.length:'bytes'),()=>assert.equal(sha256(input),digest(input)));
test('archive refuses path traversal and duplicate names',()=>{assert.throws(()=>archive([{name:'../bad',data:'a'}]));assert.throws(()=>archive([{name:'a',data:'a'},{name:'a',data:'b'}]));assert.throws(()=>archive([{name:'/bad',data:'x'}]));});
test('asset names are safe and nonempty',()=>{assert.equal(safeAssetName('CON'),'asset-CON');assert.ok(!/[\\/:*?"<>|]/.test(safeAssetName('../../X: Y')));assert.ok(safeAssetName('///'));assert.ok(safeAssetName('a'.repeat(100)).length<=64);});
for(const value of [{framesS:9},{frames:2},{frames:34},{frames:3.5},{mode:'rigged'},{phase:NaN},{phase:-.1},{phase:1.1},{start:.9,end:.4},{pigment:'yes'},{acknowledgeWarnings:1},{target:'phone'},{pose:'unknown'},[],null])test('invalid delivery settings are refused: '+JSON.stringify(value),()=>assert.throws(()=>deliveryOptions(value)));
test('binary writer copies a typed-array subview',()=>{const w=new GLBWriter('unit'),a=new Float32Array([999,1,2,3,999]),id=w.accessor(a.subarray(1,4),'VEC3',{bounds:true});a[1]=888;w.json.meshes.push({primitives:[]});const glb=readDeliveryGLB(w.finish());assert.deepEqual([...glb.accessor(id)],[1,2,3]);assert.deepEqual(glb.json.accessors[id].min,[1,2,3]);});
test('binary writer rejects empty, nonfinite, and invalid array shapes',()=>{const w=new GLBWriter();assert.throws(()=>w.finish());assert.throws(()=>w.accessor(new Float32Array([1,NaN,2]),'VEC3'));assert.throws(()=>w.accessor(new Float32Array([1,2]),'VEC3'));assert.throws(()=>w.accessor(new Int8Array([1]),'SCALAR'));});
test('GLB header corruption is refused',async()=>{const r=await buildDelivery(preset('moonbell'));for(const offset of [0,4,8,12,16]){const b=r.glb.slice();b[offset]^=255;assert.throws(()=>readDeliveryGLB(b));}assert.throws(()=>readDeliveryGLB(r.glb.subarray(0,r.glb.length-1)));});
test('warnings require explicit acknowledgement',async()=>{await assert.rejects(buildDelivery(preset('wayfarer'),{target:'crowd'}),/warning/i);const r=await buildDelivery(preset('wayfarer'),{target:'crowd',acknowledgeWarnings:true});assert.equal(r.report.technicalStatus,'warning');assert.ok(r.report.warningCount);assert.equal(r.manifest.checks.visualApproval,false);});
test('completed original parts now export without changing the source',async()=>{const g=preset('mossback'),before=JSON.stringify(g);assert.equal(deliveryEligibility(g).eligible,true);const asset=await buildDelivery(g);assert.equal(asset.manifest.geometry.allActiveGenesIncluded,true);assert.equal(JSON.stringify(g),before);});
test('abort before a build writes nothing',async()=>{const c=new AbortController();c.abort();await assert.rejects(buildDelivery(preset('moonbell'),{}, {signal:c.signal}),{name:'AbortError'});});
test('abort between motion samples writes nothing and preserves source',async()=>{const c=new AbortController(),g=preset('moonbell'),source=JSON.stringify(g);await assert.rejects(buildDelivery(g,{mode:'motion',frames:9},{signal:c.signal,onProgress:p=>{if(p.stage==='Sample motion'&&p.completed===2)c.abort();}}),{name:'AbortError'});assert.equal(JSON.stringify(g),source);});
test('output is deterministic for the same source and settings',async()=>{const g=preset('moonbell'),o={mode:'motion',frames:3},a=await buildDelivery(g,o),b=await buildDelivery(g,o);assert.equal(digest(a.glb),digest(b.glb));assert.equal(digest(a.zip),digest(b.zip));assert.equal(a.manifest.sourceSHA256,b.manifest.sourceSHA256);});
test('flat pigment does not change geometry',async()=>{const g=preset('trailhound'),a=await buildDelivery(g,{pigment:true}),b=await buildDelivery(g,{pigment:false}),x=deliveryPose(a.glb),y=deliveryPose(b.glb);assert.equal(x.length,y.length);for(let i=0;i<x.length;i++)assert.deepEqual(x[i].positions,y[i].positions);assert.notEqual(digest(a.glb),digest(b.glb));});
let eligible=0,blocked=0;
for(const model of PRESET_MODELS){test('catalog delivery gate and binary structure: '+model.id,async()=>{
  const g=preset(model.id),e=deliveryEligibility(g),unchanged=JSON.stringify(g);if(!e.eligible){blocked++;assert.ok(e.unsupportedFamilies.length);return;}eligible++;
  const result=await buildDelivery(g,{acknowledgeWarnings:true}),file=readDeliveryGLB(result.glb);assert.equal(file.json.asset.version,'2.0');assert.equal(file.json.skins,undefined);assert.equal(file.json.textures,undefined);assert.equal(file.json.animations,undefined);assert.equal(file.json.meshes.length,result.manifest.totals.meshes);assert.equal(JSON.stringify(g),unchanged);assert.equal(result.manifest.geometry.allGenesIncluded,true);assert.ok(result.glb.length<DELIVERY_LIMITS.bytes);assert.equal(result.report.gpuVerified,false);
  for(const a of file.json.accessors){const data=file.accessor(file.json.accessors.indexOf(a));for(const v of data)assert.ok(Number.isFinite(v));}
  for(const m of file.json.meshes){const p=m.primitives[0];assert.equal(p.mode,4);const positions=file.accessor(p.attributes.POSITION),normals=file.accessor(p.attributes.NORMAL),colors=file.accessor(p.attributes.COLOR_0),indices=file.accessor(p.indices);assert.equal(positions.length,normals.length);assert.equal(colors.length,positions.length);for(let i=0;i<normals.length;i+=3)assert.ok(Math.abs(Math.hypot(normals[i],normals[i+1],normals[i+2])-1)<1e-5);for(const i of indices)assert.ok(i<positions.length/3);for(const c of colors)assert.ok(c>=0&&c<=1);}
});}
test('coverage totals do not silently become full catalog approval',()=>{assert.equal(eligible,89);assert.equal(blocked,0);});
for(const id of ['wayfarer','archivist','trailhound','moonbell','glassdart','salpchain','shrinesentinel'])test('baked frames round trip to exact source samples: '+id,async()=>{
  const g=preset(id),compiler=new FoundationCompiler(g),r=await buildDelivery(g,{mode:'motion',frames:9,acknowledgeWarnings:true}),file=readDeliveryGLB(r.glb),duration=r.manifest.animation.durationSeconds;
  assert.equal(file.json.animations.length,1);assert.equal(r.manifest.animation.recommendedPlayback,'once');assert.equal(r.manifest.animation.samples,9);assert.equal(r.report.frames.length,9);
  for(let fi=0;fi<9;fi++){const s=compiler.sample({pose:'motion-cycle',phase:fi/8,garment:true,details:true}),meshes=deliveryPose(file,duration*fi/8);let max=0;assert.equal(meshes.length,s.meshes.length);for(let j=0;j<meshes.length;j++){assert.equal(meshes[j].name,s.meshes[j].name);for(let k=0;k<meshes[j].positions.length;k++)max=Math.max(max,Math.abs(meshes[j].positions[k]-s.meshes[j].positions[k]));}assert.ok(max<3e-6,'frame '+fi+' error '+max);}
});
test('between-frame animation uses linear interpolation',async()=>{const r=await buildDelivery(preset('moonbell'),{mode:'motion',frames:3}),duration=r.manifest.animation.durationSeconds,a=deliveryPose(r.glb,0),b=deliveryPose(r.glb,duration/2),m=deliveryPose(r.glb,duration/4);for(let j=0;j<m.length;j++)for(let i=0;i<m[j].positions.length;i++)assert.ok(Math.abs(m[j].positions[i]-(a[j].positions[i]+b[j].positions[i])*.5)<1e-6);});
test('motion phase subrange has relative time and records the source range',async()=>{const g=preset('archivist'),r=await buildDelivery(g,{mode:'motion',frames:3,start:.25,end:.75}),f=readDeliveryGLB(r.glb),input=f.accessor(f.json.animations[0].samplers[0].input);assert.equal(input[0],0);assert.ok(Math.abs(input.at(-1)-motionCycleTime(g.motion,.5,true))<1e-6);assert.equal(r.manifest.settings.start,.25);});
test('motion warns about open endpoints rather than forcing a loop',async()=>{const r=await buildDelivery(preset('moonbell'),{mode:'motion',frames:9});assert.ok(r.manifest.animation.endpointGapMetres>.01);assert.equal(r.manifest.animation.loopClosed,false);});
test('package contents have SHA-256 records and standard binary metadata',async()=>{const r=await buildDelivery(preset('moonbell'));assert.deepEqual(r.manifest.files.map(x=>x.name),['model.glb','source.morph.json','audit.json','README.txt']);assert.equal(r.manifest.files[0].sha256,digest(r.glb));assert.equal(new DataView(r.zip.buffer).getUint32(0,true),0x04034b50);assert.equal(r.manifest.coordinates.up,'+Y');assert.equal(r.manifest.coordinates.forward,'+Z');});

test('Node Buffer and offset views decode without leaking backing-buffer bytes',async()=>{const r=await buildDelivery(preset('moonbell')),reference=deliveryPose(r.glb),storage=Buffer.alloc(r.glb.length+16);Buffer.from(r.glb).copy(storage,8);const view=storage.subarray(8,8+r.glb.length),decoded=deliveryPose(view);assert.equal(decoded.length,reference.length);for(let i=0;i<decoded.length;i++){assert.deepEqual(decoded[i].positions,reference[i].positions);assert.deepEqual(decoded[i].normals,reference[i].normals);assert.deepEqual(decoded[i].indices,reference[i].indices);}});
test('exported animated samples all receive binary round-trip checks',async()=>{const r=await buildDelivery(preset('moonbell'),{mode:'motion',frames:3});assert.equal(r.report.internalGLBRoundTrip.checkedSamples,3);assert.ok(r.report.internalGLBRoundTrip.maxPositionError<1e-5);});
test('binary byte budget is enforced',()=>{const w=new GLBWriter();w.accessor(new Float32Array([1,2,3]),'VEC3');w.json.meshes.push({primitives:[]});assert.throws(()=>w.finish(20),/limit/);});
