import {escapeHTML as esc,icon} from './icons.js';
import {PRESET_MODELS} from '../core/presets.js';
import {MIX_CHANNELS} from '../core/mixer.js';
import {MOTION_CLIPS,MOTION_LAYERS} from '../core/motion.js';
import {PATTERNS,MICRO_SURFACES,SURFACE_PRESETS,appearanceLayers} from '../core/surfaces.js';
const options=(items,value)=>items.map(item=>{const [v,label]=typeof item==='string'?[item,item]:item;return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(label)}</option>`;}).join('');
const slider=(attr,label,value,min=0,max=1,step=.01,disabled=false)=>`<label class="range-label"><span>${label}</span><output>${Number(value).toFixed(step===1?0:2)}</output><input type="range" ${attr} value="${value}" min="${min}" max="${max}" step="${step}" ${disabled?'disabled':''} aria-label="${label}"></label>`;
export function renderMixer(m){
  if(!m)return '';
  const s=m.settings;
  return `<section class="mixer-intro"><span class="eyebrow">RECIPE MIXER / A + B</span><h3>Combine two creatures</h3><p class="fine-copy">Mix immutable source recipes. Preview first. Apply creates one undo step.</p></section>
  <div class="mix-sources">${['a','b'].map(slot=>`<section class="mix-source"><span class="source-badge">${slot.toUpperCase()}</span><div><strong>${esc(m.sources[slot].name)}</strong><small>${m.sources[slot].nodes.length} nodes · ${m.sources[slot].parts.length} genes</small></div><select data-mix-source="${slot}" aria-label="Source ${slot.toUpperCase()}">${options([['snapshot','Captured creature'],['file','Imported recipe'],...PRESET_MODELS.map(p=>[p.id,p.label])],m.labels[slot])}</select><div class="mix-source-actions"><button data-mix-action="capture" data-slot="${slot}">Capture current</button><button data-mix-action="import-source" data-slot="${slot}">Import JSON</button></div></section>`).join('')}</div>
  <section class="inspector-section"><div class="section-title">MASTER CROSSFADE <span>A → B</span></div>${slider('data-mix-master','All unlocked channels',Object.entries(s.channels).filter(([k])=>!s.locks[k]).reduce((total,[,v],i,arr)=>total+v/arr.length,0))}<div class="mix-endpoints"><button data-mix-action="endpoint" data-value="0">100% A</button><button data-mix-action="endpoint" data-value="0.5">50 / 50</button><button data-mix-action="endpoint" data-value="1">100% B</button></div></section>
  <section class="inspector-section"><div class="section-title">INDEPENDENT CHANNELS <span>LOCK TO FREEZE</span></div>${Object.entries(MIX_CHANNELS).map(([key,label])=>`<div class="mix-channel">${slider(`data-mix-channel="${key}"`,label,s.channels[key],0,1,.01,s.locks[key])}<label class="mix-lock"><input type="checkbox" data-mix-lock="${key}" ${s.locks[key]?'checked':''} aria-label="Lock ${label}"><span>${s.locks[key]?'Locked':'Lock'}</span></label></div>`).join('')}<label class="select-row">Body graph<select data-mix-topology aria-label="Body graph">${options([['auto','A below 50%; B above'],['a','Keep source A graph'],['b','Keep source B graph']],s.topology)}</select></label><p class="fine-copy">Matching dimensions blend. Body graph, variants, and symmetry switch. Unmatched appendages shrink in or out.</p></section>
  <section class="inspector-section"><div class="section-title">SEEDED VARIATION</div>${slider('data-mix-mutation','Mutation amount',s.mutation)}<label class="select-row">Seed<input type="number" data-mix-seed min="0" max="4294967295" step="1" value="${s.seed}" aria-label="Mixer seed"></label><button class="quiet full-width" data-mix-action="random">${icon('dice')} Randomize unlocked channels</button></section>
  <div class="mix-status" id="mix-status" aria-live="polite">${mixStatus(m)}</div><div class="mix-commit"><button class="quiet" data-mix-action="preview">Preview</button><button class="primary" data-mix-action="apply">Apply mix</button><button class="quiet" data-mix-action="cancel">Cancel</button></div>
  <section class="inspector-section"><div class="section-title">PORTABLE RECIPE</div><p class="fine-copy">A recipe stores both sources, channel values, locks, and seed. A blueprint stores only the result.</p><div class="recipe-buttons"><button class="quiet" data-mix-action="export">Export recipe</button><button class="quiet" data-mix-action="import">Import recipe</button><button class="quiet" data-mix-action="save">Save on device</button><button class="quiet" data-mix-action="load">Recall saved</button></div></section>`;
}
export function mixStatus(m){return `${m.previewing?'LIVE PREVIEW — not applied':'MIXER READY'}${m.stats?`<br>${m.stats.bodyNodes} nodes · ${m.stats.genes} genes · ${m.stats.patternLayers} pigment layers`:''}${m.notes.map(n=>`<p>${esc(n)}</p>`).join('')}`;}
export function renderMotion(m){
  return `<section class="mixer-intro"><span class="eyebrow">PROCEDURAL MOTION MIXER</span><h3>Blend movement states</h3><p class="fine-copy">State weights are normalized. Secondary layers use separate gains. Zero state weights select idle.</p></section>
  <div class="motion-presets">${Object.entries(MOTION_CLIPS).map(([key,clip])=>`<button data-action="motion-preset" data-clip="${key}" class="${m.weights[key]===1?'active':''}">${clip.label}</button>`).join('')}</div>
  <section class="inspector-section"><div class="section-title">TRAVEL CONTROLLER</div><label class="select-row">Medium<select data-travel-medium aria-label="Travel medium">${options([['ground','Ground'],['water','Water / reef tank'],['air','Air / sky course']],m.travel.medium)}</select></label>${slider('data-motion-group="travel" data-motion-key="speed"','Cruise speed',m.travel.speed,.4,9)}${slider('data-motion-group="travel" data-motion-key="climb"','Vertical speed',m.travel.climb,.3,6)}${slider('data-motion-group="travel" data-motion-key="bank"','Visual bank',m.travel.bank,0,.7)}<p class="fine-copy">Water and air use a bounded, three-axis arcade controller. Space or E rises. Q or Ctrl descends. No fluid, lift, or drag solver is used. Ground uses the original walk controller.</p></section>
  <section class="inspector-section"><div class="section-title">BODY DEFORMATION</div><label class="select-row">Wave<select data-body-wave aria-label="Body wave">${options([['rigid','Rigid / no wave'],['lateral','Lateral / eel'],['vertical','Vertical / ribbon'],['pulse','Pulse / medusa']],m.bodyWave.kind)}</select></label>${slider('data-motion-group="bodyWave" data-motion-key="amplitude"','Body wave amplitude',m.bodyWave.amplitude,0,.65)}${slider('data-motion-group="bodyWave" data-motion-key="frequency"','Body wave frequency',m.bodyWave.frequency,.1,3)}${slider('data-motion-group="bodyWave" data-motion-key="wavelength"','Body wavelength',m.bodyWave.wavelength,.6,8)}<p class="fine-copy">The wave deforms creature skin and moves attachment anchors. It does not change the collider or a humanoid skeleton.</p></section>
  <section class="inspector-section"><div class="section-title">STATE WEIGHTS</div>${Object.entries(MOTION_CLIPS).map(([key,clip])=>slider(`data-motion-group="weights" data-motion-key="${key}"`,clip.label+' weight',m.weights[key])).join('')}</section>
  <section class="inspector-section"><div class="section-title">GAIT SETTINGS</div>${slider('data-motion-key="tempo"','Tempo',m.tempo,.1,3)}${slider('data-motion-key="stride"','Stride multiplier',m.stride,.1,2)}${slider('data-motion-key="lift"','Foot lift multiplier',m.lift,.1,2)}${slider('data-motion-key="phaseLag"','Pair phase offset',m.phaseLag,0,1)}</section>
  <section class="inspector-section"><div class="section-title">SECONDARY LAYER GAINS</div>${Object.entries(MOTION_LAYERS).map(([key,label])=>slider(`data-motion-group="layers" data-motion-key="${key}"`,label,m.layers[key],0,2)).join('')}</section>
  <p class="warning-copy">Motion states control the pose. The Travel medium selects movement physics. Wing size and fin size do not change lift or thrust.</p>`;
}
export function renderSurfaceLayers(a){
  return `<div class="inspector-section"><div class="section-title">MATERIAL RECIPES</div><div class="material-recipes">${Object.entries(SURFACE_PRESETS).map(([key,p])=>`<button data-action="surface-preset" data-preset="${key}">${p.label}</button>`).join('')}</div></div>
  <div class="inspector-section"><div class="section-title">LAYERED PIGMENT <span>MAXIMUM 4</span></div><p class="fine-copy">Weights combine patterns on the surface. All weights at zero remove the pattern.</p>${appearanceLayers(a).map((l,i)=>`<details class="skin-layer" ${i===0?'open':''}><summary>Layer ${i+1} · ${esc(l.pattern)} <small>${Math.round(l.weight*100)}%</small></summary><label class="select-row">Pattern<select data-layer-index="${i}" data-layer-field="pattern" aria-label="Layer ${i+1} pattern">${options(PATTERNS,l.pattern)}</select></label>${slider(`data-layer-index="${i}" data-layer-field="weight"`,'Layer '+(i+1)+' weight',l.weight)}${slider(`data-layer-index="${i}" data-layer-field="scale"`,'Layer '+(i+1)+' scale',l.scale,2,12,.1)}${slider(`data-layer-index="${i}" data-layer-field="angle"`,'Layer '+(i+1)+' angle',l.angle,-3.14,3.14)}${slider(`data-layer-index="${i}" data-layer-field="warp"`,'Layer '+(i+1)+' warp',l.warp,0,2)}${i?`<button class="quiet danger" data-action="remove-layer" data-layer="${i}">Remove layer</button>`:''}</details>`).join('')}<button class="quiet full-width" data-action="add-layer" ${a.layers.length>=3?'disabled':''}>${icon('plus')} Add pigment layer</button></div>
  <div class="inspector-section"><div class="section-title">SURFACE RESPONSE</div><label class="select-row">Texture seed<input type="number" data-surface-seed min="0" max="4294967295" step="1" value="${a.textureSeed}" aria-label="Texture seed"></label><label class="select-row">Microtexture<select data-surface-micro aria-label="Microtexture">${options(MICRO_SURFACES,a.micro)}</select></label>${slider('data-range="strength"','Pigment strength',a.strength)}${slider('data-range="roughness"','Roughness',a.roughness,.2,1)}${slider('data-range="metalness"','Metalness',a.metalness)}${slider('data-range="relief"','Microtexture relief',a.relief,0,.15,.001)}${slider('data-range="emission"','Emission',a.emission,0,2)}</div>`;
}
