/** Shared local tool dialog. No network or application-state dependency. */
export function toolDialog(id,title){
  document.getElementById(id)?.close();
  if(!document.getElementById('tool-dialog-style')){
    const style=document.createElement('style');style.id='tool-dialog-style';style.textContent=`
.tool-dialog{box-sizing:border-box;width:min(760px,94vw);max-height:91vh;border:1px solid #b9c8c0;border-radius:14px;padding:0;background:#f7f8f3;color:#263d35;box-shadow:0 24px 90px #0b21184d;font:14px/1.5 system-ui,sans-serif;overflow:auto}.tool-dialog::backdrop{background:#0d231cad;backdrop-filter:blur(3px)}.tool-dialog header{display:flex;align-items:center;gap:16px;padding:22px 26px;border-bottom:1px solid #d5ddd4}.tool-dialog h2{font:600 23px/1.2 system-ui;margin:0;flex:1}.tool-dialog .tool-body{padding:20px 26px}.tool-dialog p{line-height:1.55;margin:9px 0}.tool-dialog .tool-eyebrow{font-size:10px;letter-spacing:1.7px;text-transform:uppercase;color:#577564;margin:0 0 6px}.tool-dialog button,.tool-dialog a.tool-download{font:inherit;cursor:pointer;border:1px solid #bccbc1;background:#fff;color:#263d35;padding:9px 13px;border-radius:6px;text-decoration:none;text-align:center}.tool-dialog button:disabled{opacity:.45;cursor:default}.tool-dialog button.tool-primary{background:#315e4b;border-color:#315e4b;color:#fff}.tool-dialog label{display:block;font-size:12px}.tool-dialog select,.tool-dialog input[type=number]{box-sizing:border-box;width:100%;font:inherit;padding:8px;border:1px solid #bccbc1;border-radius:5px;background:#fff;color:#253b31;margin-top:5px}.tool-dialog .tool-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:18px 0}.tool-dialog .tool-hint{font-size:12px;color:#5e7267}.tool-dialog .tool-notice{padding:12px 14px;border-left:3px solid #5b866f;background:#e8eee5;margin:14px 0}.tool-dialog .tool-warning{border-color:#bd8a36;background:#f5eedb}.tool-dialog .tool-error{border-color:#b05444;background:#f5e6e0}.tool-dialog .tool-row{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0;align-items:center}.tool-dialog progress{width:100%;height:7px;accent-color:#456f57}.tool-dialog .tool-check{display:flex;align-items:flex-start;gap:8px;margin:12px 0}.tool-dialog .tool-check input{margin-top:4px}.tool-dialog [hidden]{display:none!important}.tool-dialog .tool-results{border-top:1px solid #cbd8ce;margin-top:22px;padding-top:14px}.tool-dialog .tool-check-result{display:grid;grid-template-columns:150px 1fr;gap:10px;padding:9px 0;border-top:1px solid #e1e7df;font-size:12px}.tool-dialog .tool-check-result b{font-weight:600}.tool-dialog pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:240px;overflow:auto;background:#eef1e9;padding:12px;font-size:11px}.tool-dialog .tool-status{min-height:22px;font-size:12px}@media(max-width:540px){.tool-dialog header,.tool-dialog .tool-body{padding:18px}.tool-dialog .tool-grid{grid-template-columns:1fr}.tool-dialog .tool-check-result{grid-template-columns:1fr;gap:2px}}
`;document.head.append(style);
  }
  const dialog=document.createElement('dialog');dialog.id=id;dialog.className='tool-dialog';dialog.setAttribute('aria-label',title);
  const header=document.createElement('header'),heading=document.createElement('h2'),close=document.createElement('button'),body=document.createElement('div');heading.textContent=title;close.type='button';close.textContent='Close';close.dataset.toolClose='';close.setAttribute('aria-label','Close '+title);body.className='tool-body';header.append(heading,close);dialog.append(header,body);document.body.append(dialog);
  close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();return {dialog,body};
}
export function localDownload(data,name,type='application/json'){
  const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);
}
