/** Continuous, normalized mixer channels. These clips do not apply physical forces. */
const clip = (label, extra) => ({
  label,
  rate: 0.65,
  stride: 0,
  lateral: 0,
  lift: 0,
  stance: 0.6,
  bob: 0.025,
  sway: 0.012,
  pitch: 0,
  flap: 0,
  tail: 0.2,
  jaw: 0.02,
  tuck: 0.18,
  wingRate: 1,
  wingOpen: 1,
  pulse: 0,
  paddle: 0,
  comb: 0,
  pump: 0,
  spread: 0,
  spin: 0,
  fold: 0,
  scull: 0,
  ...extra,
});
export const FRONTIER_MOTION = Object.freeze({
  combbeat: clip('Comb wave', { comb: 1, wingRate: 1.5, bob: 0.008 }),
  chainpump: clip('Linked pulse', { pump: 1, pulse: 0.7, wingRate: 0.7, bob: 0.028 }),
  radialstroke: clip('Radial stroke', { spread: 1, pump: 0.25, wingRate: 0.65, bob: 0.055 }),
  metachronal: clip('Oar sequence', { scull: 1, paddle: 0.6, wingRate: 1.15, tail: 0.4 }),
  canopy: clip('Canopy breath', { spread: 0.85, fold: 0.25, wingRate: 0.36, bob: 0.085 }),
  corkscrew: clip('Helix turn', { spin: 0.7, wingRate: 0.65, bob: 0.035 }),
  turbines: clip('Duct rotation', { spin: 1, wingRate: 2.4, bob: 0.012 }),
  concertina: clip('Pleat stroke', { fold: 1, flap: 0.35, wingRate: 0.85, bob: 0.045 }),
});
