"""Assemble actual CPU renders. Run npm run review:frontier -- --render first.
Requires Pillow. Geometry and its colors are not painted over or replaced.
"""
from pathlib import Path
import json
from PIL import Image, ImageDraw, ImageFont
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'test-results/v7-frontier-batch'
OUT=ROOT/'test-results'
report=json.loads((SOURCE/'report.json').read_text())
FONT=Path('/usr/share/fonts/truetype/dejavu')
def font(size,bold=False):
    try:return ImageFont.truetype(str(FONT/('DejaVuSans-Bold.ttf' if bold else 'DejaVuSans.ttf')),size)
    except OSError:return ImageFont.load_default()
BG='#f3f5f1';INK='#203b3d';MUTED='#5d7070'
notes={'comblantern':'Eight rails of hinged comb plates','salpchain':'Five phase-offset pump modules','starweaver':'Five-arm radial web',
       'velvetslug':'Frilled mantle and branching plumes','oarshrimp':'Staggered banks of paddles','twinjet':'Paired open pump tubes',
       'hoopglider':'Closed oval wing and suspended keel','sievewisp':'Double bristle canopy','prismkite':'Open diamond sail cells',
       'screwdrifter':'Continuous helical ribbons','ductmanta':'Paired contra-rotating ducts','pleatdrake':'Three pairs of hinged pleat fans'}
cell=370;gap=16;margin=28;w=margin*2+cell*3+gap*2;h=180+4*(cell+74)+3*gap+76
sheet=Image.new('RGB',(w,h),BG);d=ImageDraw.Draw(sheet)
d.text((margin,24),'MORPH LAB / STRANGE FORMS',font=font(30,True),fill=INK)
d.text((margin,72),'12 procedural models  /  6 water + 6 air',font=font(23),fill=INK)
d.text((margin,114),'Rendered from the same geometry code used by the game adapter.',font=font(17),fill=MUTED)
d.text((margin,140),'CPU pigment preview. No image-generated replacement models.',font=font(16),fill=MUTED)
for i,row in enumerate(report['records']):
    x=margin+i%3*(cell+gap);y=180+i//3*(cell+74+gap)
    im=Image.open(SOURCE/(row['id']+'-2.png')).convert('RGB').resize((cell,cell),Image.Resampling.LANCZOS);sheet.paste(im,(x,y))
    d.text((x+9,y+cell+8),row['label'],font=font(21,True),fill=INK)
    d.text((x+9,y+cell+37),notes[row['id']],font=font(14),fill=MUTED)
    d.text((x+9,y+cell+57),row['medium'].upper(),font=font(11,True),fill=MUTED)
d.text((margin,h-52),'Each model is fitted separately. All motion samples of one model share one camera scale.',font=font(14),fill=MUTED)
d.text((margin,h-29),'Technical checks are not production approval. GPU materials and physics are not verified.',font=font(14),fill=MUTED)
sheet.save(OUT/'v7-model-library.png',optimize=True)
selected=[('salpchain','Linked pulse'),('starweaver','Radial stroke'),('sievewisp','Canopy breath'),('pleatdrake','Pleat stroke')]
frames=[];cell=370;w=28*2+cell*2+16;h=105+2*(cell+48)+16+55
for phase in range(8):
    frame=Image.new('RGB',(w,h),BG);d=ImageDraw.Draw(frame)
    d.text((28,20),'MORPH LAB / MOTION SAMPLES',font=font(25,True),fill=INK)
    d.text((28,60),f'Actual CPU geometry  |  t = {phase/4:.2f} s  |  fixed camera per model',font=font(14),fill=MUTED)
    for i,(key,label) in enumerate(selected):
        x=28+i%2*(cell+16);y=105+i//2*(cell+48+16)
        im=Image.open(SOURCE/f'{key}-{phase}.png').convert('RGB').resize((cell,cell),Image.Resampling.LANCZOS);frame.paste(im,(x,y))
        d.text((x+8,y+cell+12),label,font=font(18,True),fill=INK)
    d.text((28,h-30),'Eight sampled frames repeat; not a seamless clip or a physics capture.',font=font(13),fill=MUTED)
    frames.append(frame)
frames[0].save(OUT/'v7-motion-samples.gif',save_all=True,append_images=frames[1:],duration=250,loop=0,optimize=False)
# Pattern / height atlas is optional, generated by frontier-swatches.mjs.
meta=OUT/'v7-swatches/report.json'
if meta.exists():
    entries=json.loads(meta.read_text());cell=275;w=28*2+4*cell+3*16;h=150+2*(cell+115)+16+58
    sheet=Image.new('RGB',(w,h),BG);d=ImageDraw.Draw(sheet)
    d.text((28,24),'MORPH LAB / PROCEDURAL SURFACES',font=font(28,True),fill=INK)
    d.text((28,71),'Eight new pigment patterns and their generated height textures.',font=font(18),fill=MUTED)
    d.text((28,107),'Per-pixel planar fields, one palette and seed. CPU functions, not GPU materials.',font=font(14),fill=MUTED)
    for i,row in enumerate(entries):
        x=28+i%4*(cell+16);y=150+i//4*(cell+115+16)
        im=Image.open(OUT/'v7-swatches'/f"{row['id']}.png").convert('RGB').resize((cell,cell),Image.Resampling.LANCZOS);sheet.paste(im,(x,y))
        d.text((x+5,y+cell+6),row['label'],font=font(17,True),fill=INK)
        d.text((x+5,y+cell+31),row['pattern'],font=font(13),fill=MUTED)
        strip=Image.open(OUT/'v7-swatches'/f"{row['id']}-height.png").convert('RGB').resize((48,48),Image.Resampling.NEAREST);sheet.paste(strip,(x+5,y+cell+53))
        d.text((x+64,y+cell+62),row['micro']+' / height',font=font(12),fill=MUTED)
    d.text((28,h-31),'Relief, metalness, emission and roughness require a separate GPU material check.',font=font(14),fill=MUTED)
    sheet.save(OUT/'v7-surface-atlas.png',optimize=True)
print('Created actual-model sheet, motion GIF, and optional surface atlas.')
